project:
  type: website
  preview:
    port: 4200
    browser: true

# These cannot be used as variables. They are reserved for the project configuration.
website:
  title: "Turing.jl"
  site-url: https://turinglang.org
  site-path: "/"
  favicon: "assets/favicon.ico"
  search: 
    location: navbar
    type: overlay
    # keyboard-shortcut: ["?", "H", "f"]
  navbar:
    logo: "assets/images/turing-logo.svg"
    background: "#073c44"
    foreground: "#ffffff"
    left:
      - href: dev/docs/using-turing/get-started
        text: Get Started
      - href: dev/tutorials/00-introduction
        text: Tutorials
      - href: library/
        text: Library API
      - href: news/
        text: News
      - href: team/
        text: Team
    tools:
      - icon: twitter
        href: https://x.com/TuringLang
        text: Turing Twitter
      - icon: github
        href: https://github.com/TuringLang/Turing.jl
        text: Turing GitHub

  sidebar:
    - id: documentation
      collapse-level: 1
      contents: 
        - section: "Documentation"
          href: dev/docs/index.qmd
          contents:
          - section: "Using Turing"
            collapse-level: 1
            # href: dev/docs/using-turing/get-started
            contents: 
              - dev/docs/using-turing/getting-started/index.qmd
              - text: "Quick Start"
                href: dev/docs/using-turing/quick-start/index.qmd
              - dev/docs/using-turing/guide/index.qmd
              - dev/docs/using-turing/advanced-usage/index.qmd
              - dev/docs/using-turing/automatic-differentiation/index.qmd
              - dev/docs/using-turing/performance-tips/index.qmd
              - dev/docs/using-turing/using-dynamichmc/index.qmd
              - dev/docs/using-turing/sampler-visualization/index.qmd
              - text: "External Samplers"
                href: dev/docs/using-turing/external-samplers/index.qmd

          - section: "Tutorials"
            contents: 
              - dev/docs/tutorials/introduction/index.qmd

  
  page-footer:
    background: "#073c44"
    left: |
      Turing is created by <a href="http://mlg.eng.cam.ac.uk/hong/" target="_blank">Hong Ge</a>, and lovingly maintained by the <a href="https://github.com/TuringLang/Turing.jl/graphs/contributors" target="_blank">core team</a> of volunteers. <br>
      The contents of this website are © 2024 under the terms of the <a href="https://github.com/TuringLang/Turing.jl/blob/master/LICENCE" target="_blank">MIT License</a>. 

    right:
      - icon: twitter
        href: https://x.com/TuringLang
        aria-label: Turing Twitter
      - icon: github
        href: https://github.com/TuringLang/Turing.jl
        aria-label: Turing GitHub

  back-to-top-navigation: true
  repo-url: https://github.com/TuringLang/turinglang.github.io/
  repo-actions: [edit, issue]
  repo-link-target: _blank
  page-navigation: true

format:
  html:
    theme:
      light: cosmo
      # dark: [cosmo, theming/theme-dark.scss]
    css: styles.css
    toc: true
    smooth-scroll: true
    code-overflow: wrap
    output-block-background: true
    # code-block-border-left: true
    # code-line-numbers: true

# execute:
#   freeze: auto

# Global Variables to use in any qmd files using:
# {{< meta site-url >}}
site-url: https://turinglang.org/turing-test-website
get-started: dev/docs/using-turing/get-started
tutorials-intro: dev/docs/tutorials/00-introduction