---
title: Turing.jl Newsletter 11
description: The fortnightly newsletter for the Turing.jl probabilistic programming language
categories:
  - Newsletter
author:
  - name: The TuringLang team
    url: /team/
date: 2025-07-25
---

**Libtask and Turing.jl**

The new versions of Libtask and AdvancedPS have now been integrated into Turing.jl proper. You shouldn't see any changes, except that particle MCMC methods will now run a lot faster!

(Do note that these won't work on Julia 1.12 just yet as it is somewhat tightly coupled to Julia internals; we're working on a fix but if you really want to use Turing on 1.12 right now you will have to stick to Turing ≤ 0.39.6.)

**Progress bars**

AbstractMCMC 5.7 is released with the new progress bars!
By default you get a single progress bar (but with more frequent updates).
You need to opt-in to per-chain progress bars with `sample(...; progress=:perchain)`

**ADTests categories**

[The list of models has been split up](https://turinglang.org/ADTests/) into different sections to make it a bit easier to read.
I'm keen to add more examples of integrations with other packages — if you have a Turing model that uses functionality from a different package inside it, please do get in touch with an example!
(I'll be adding things like DifferentialEquations, HiddenMarkovModels, and AbstractGPs soon, since those are already in our docs)

**Community meetings**

The Turing.jl developer team usually meet once every week; we're thinking of opening some of these meetings to be public (perhaps once a month) and would like to gauge whether there's any interest in this.
Our current thinking is that these meetings would be something along the lines of:

- 3 guests with 1 topic each, 10 minutes each: these would be user-submitted and could really be anything you wanted to talk about, e.g. how to write a model, what samplers to use, ... And basic stuff is totally fine as that means more people get to learn how to do Bayesian modelling :)
- 10 minutes from us on "where Turing is going"
- 20 minutes free Q&A

If you would be interested in attending such a meeting or bringing along a topic, do [let us know on Slack](https://julialang.slack.com/archives/CCYDC34A0/p1753712389947349)!
